### PR TITLE
Feature/issue 8 rest client 180 compat

### PR DESCRIPTION
**Pull request by gkellogg**
This does some minimal updates for RSpec 3 and checks the arity of `RestClient::Response.create` to allow it to be used with a newer version of rest-client.

### CODE REVIEW

**Comment by cbeer** [comment]
:+1:

**Comment by ndushay** [comment]
:thumbsup:

**Comment by crohr** [comment]
Thanks for this! Some cleanup was much needed.

**Comment by crohr** [comment]
v1.4.0 released on rubygems.org

**Pull request merged**
